[tool.poetry]
name = "filescan"
version = "0.0.1"
description = "A tool for tracking files and Python source"
authors = ["Steve Holden <steve@holdenweb.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2-binary = "^2.9.9"
mongoengine = "^0.27.0"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
