"""empty message

Revision ID: 236ace2b5fcf
Revises: 79a7aa53d735
Create Date: 2024-01-05 17:45:31.328964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "236ace2b5fcf"
down_revision: Union[str, None] = "79a7aa53d735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_checksum_checksum", table_name="checksum")
    op.create_index(op.f("ix_checksum_checksum"), "checksum", ["checksum"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checksum_checksum"), table_name="checksum")
    op.create_index("ix_checksum_checksum", "checksum", ["checksum"], unique=False)
    # ### end Alembic commands ###
