"""Correct relationship between RunLog and Archive. I hope.!

Revision ID: 6af913e7a179
Revises: d9e23a3d2ca2
Create Date: 2025-04-05 15:44:18.013520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6af913e7a179"
down_revision: Union[str, None] = "d9e23a3d2ca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
