"""empty message

Revision ID: 79a7aa53d735
Revises: d2789c60a945
Create Date: 2024-01-05 17:41:23.196353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79a7aa53d735"
down_revision: Union[str, None] = "d2789c60a945"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_checksum_checksum"), "checksum", ["checksum"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checksum_checksum"), table_name="checksum")
    # ### end Alembic commands ###
