"""empty message

Revision ID: d2789c60a945
Revises:
Create Date: 2024-01-04 18:07:38.390100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d2789c60a945"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("rectype", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive")),
    )
    op.create_table(
        "checksum",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checksum")),
    )
    op.create_table(
        "runlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("when_run", sa.DateTime(), nullable=False),
        sa.Column("rootdir", sa.String(), nullable=False),
        sa.Column("files", sa.Integer(), nullable=False),
        sa.Column("known", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("unchanged", sa.Integer(), nullable=False),
        sa.Column("new_files", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runlog")),
    )
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("dirpath", sa.String(), nullable=False),
        sa.Column("modified", sa.Float(), nullable=False),
        sa.Column("checksum_id", sa.Integer(), nullable=True),
        sa.Column("seen", sa.Boolean(), nullable=False),
        sa.Column("filesize", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["checksum_id"],
            ["checksum.id"],
            name=op.f("fk_location_checksum_id_checksum"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location")),
    )
    op.create_index(
        op.f("ix_location_checksum_id"), "location", ["checksum_id"], unique=False
    )
    op.create_table(
        "tokenpos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("checksum_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("pos", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["checksum_id"],
            ["checksum.id"],
            name=op.f("fk_tokenpos_checksum_id_checksum"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokenpos")),
    )
    op.create_index(
        op.f("ix_tokenpos_checksum_id"), "tokenpos", ["checksum_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokenpos_checksum_id"), table_name="tokenpos")
    op.drop_table("tokenpos")
    op.drop_index(op.f("ix_location_checksum_id"), table_name="location")
    op.drop_table("location")
    op.drop_table("runlog")
    op.drop_table("checksum")
    op.drop_table("archive")
    # ### end Alembic commands ###
